### ISSUE TITLE
luna-studio on windows 8 not installing

### ISSUE THREAD

**Issue by ipmurali** [luna/luna-manager#122] opened 2018-01-18 11:16 UTC
I am new to luna...
trying to install on Windows 8... but it's neither installing nor giving any error message when I am double clicking the exe file.

**Below are my system details**
Windows 8.1 Pro
Processor Intel i5-2520M @ 2.50 GHz
RAM 8GB
64 bit
Thinkpad T520

**Comment by luan373** [comment] 2018-01-19 23:11
I've the same problem :(

Windows 10 here

**Comment by wdanilo** [comment] 2018-01-20 01:59
Does 1.0.1 version fix this issue for you guys?

**Comment by ipmurali** [comment] 2018-01-20 07:22
In the site(http://www.luna-lang.org/) i can see only 1.0 beta version, where will get 1.0.1 version?

**Comment by wdanilo** [comment] 2018-01-21 00:29
Oh, I did not think it would be misleading. We have to think how to improve it - if you have any idea how to make it better on the website, please tell me. 

The thing is - you can download the Luna Installer once and use it many times. It will always allow you to choose the most recent Luna version from its drop-down list. Any version with 3 numbers, like `1.0.x` is a "nightly" version and we don't want to show it on the website.

**Comment by KyleHerndon** [comment] 2018-02-12 05:11
Just wanted to say that this is still an issue for me on Windows 10. I run the installer, it asks for additional permissions which I confirm, but then I get no additional information. No error reported, no installer GUI. 

If you need someone to test potential fixes, I am available.

**Comment by wdanilo** [comment] 2018-02-12 05:48
Such output such never appear there. Installer should only inform about progress etc. @sylwiabr you have to see it.

**Comment by sylwiabr** [comment] 2018-02-12 08:22
@KyleHerndon can you please try to run `lunaInstaller.exe` from command line (probably with administrator privileges) and check if there is any error? It looks like missing dependency for electron application.

**Comment by KyleHerndon** [comment] 2018-02-14 03:46
When I run lunaInstaller.exe from the command line instead of luna-manager.exe, it immediately terminates with no output.

**Comment by sylwiabr** [comment] 2018-08-03 11:10
@KyleHerndon  @ipmurali can you check the newest Installer available on the website?

**Comment by KyleHerndon** [comment] 2018-08-03 16:32
I can confirm that the new installer works on my system running Windows 10 and that it launches successfully.

**Comment by wdanilo** [comment] 2018-08-03 23:09
I'm more than happy to see this issue is getting finally resolved! I'm closing this ticket for now. If anyone will see this bug coming bag, please re-open. Good job everyone!

**Closed by wdanilo** 2018-08-03 23:09 UTC
