### ISSUE TITLE
Installation did not finish correctly; cannot uninstall

### ISSUE THREAD

**Issue by BatmanAoD** [luna/luna-manager#116] opened 2018-01-17 17:09 UTC
I'm on 64-bit Windows 7.

I ran Luna Manager and installed 1.0 Beta. The installation hung at "90% complete"; after waiting what felt like a long time (unfortunately I don't remember how long, but I think it was at least fifteen minutes and probably closer to half an hour), I closed the manager. (If there's a button to cancel installation, I may have clicked that.)

I noticed that LunaStudio appeared in my Start menu, so I opened it to see if the installation worked. The window opened, but the text "Fetching tutorials list..." never went away. I left the window open overnight, with no change.

In "Add or Remove Programs", I don't see entries for either LunaStudio or Luna Manager. Re-running the Luna Manager, it looks like there's no "uninstall" option, and the "Install" option gives an error message saying that Luna 1.0 has already been installed.

How do I uninstall and try again?

**Comment by chancyk** [comment] 2018-01-17 22:02
I'm having the same experience on Windows 7 64-bit Pro. The installer seems hangs at 90% and doesn't appear to be doing anything.

**Comment by kustosz** [comment] 2018-01-22 09:17
@sylwiabr @piotrMocz Do you need any more information to resolve the issue?

**Comment by sylwiabr** [comment] 2018-01-22 16:54
@BatmanAoD Probably copying files to `$HOME/.luna` didn't finish. If you want to give it a try you can delete `$HOME/.luna` folder (if it exist) and run it once again. To remove Luna Studio completely from your computer you need to:
1. remove  `$HOME/.luna`  
2. open console with Administrator privileges and run `C:\Program Files\LunaStudio\1.0\config\windows\uninstallAll.bat`
3. remove  `C:\Program Files\LunaStudio` folder

Windows uninstaller will be provided in the future, details will be in this issue: https://github.com/luna/luna-manager/issues/115

We will also increase verbosity for windows installations (copying files is quite slow there) https://github.com/luna/luna-manager/issues/130

**Comment by piotrMocz** [comment] 2018-01-22 18:37
Hey @BatmanAoD, I'm not proud of what I'm going to suggest but this may be a good short term fix (and we'll investigate the permissions issue in the meantime).

Could you try re-running all the three steps @sylwiabr has outlined to remove any versions of Luna Studio you have on your computer? Then it would be the safest to restart the machine (if that's a possibility) and install Luna all over again.

Based on our experience, the "permissions denied" error when moving files is actually very inconclusive on Windows. As said before, we will investigate.

**Comment by BatmanAoD** [comment] 2018-01-22 19:16
@piotrMocz I understand--I've seen very strange permissions errors before! (Once I had a file called `C:\Program` that somehow got created and couldn't be deleted except in safe mode.)

I probably won't be able to do this today, but I'll let you know when I get a chance.

**Comment by BatmanAoD** [comment] 2018-01-27 04:24
Okay, I followed your advice, running the `uninstallAll` script for both `1.0` and `current`, deleting `~/.luna`, and deleting the `LunaStudio` program folder.

Then I tried again to install the beta release, and got what looks like the same `tar` error as above. I tried again as an administrator and got the same result.

**Comment by BatmanAoD** [comment] 2018-02-12 19:53
I've tried installing the 1.1 Beta release on a fresh Windows 10 install; I got what appeared to be the same error, even after running the installer as an administrator.

Now I'm wondering how I ever got as far as I did in the install...

**Comment by sylwiabr** [comment] 2018-02-13 06:25
ok so this is connected with issue https://github.com/luna/luna-manager/issues/149 and is caused by windows `MAX_PATH`. We will try to solve it as soon as possible. Uninstalling with Control Panel should work then.

**Comment by CaiusTSM** [comment] 2018-02-14 04:37
I am having the same issue on windows 7 64 bit with version 1.1. I deleted everything containing "luna" from my c drive and also deleted also registry entries containing "luna". I also removed a bunch of things from my system path to shorten it. But it still hangs at 90%. Not having a more details option makes it hard to tell what is going on.

**Comment by BatmanAoD** [comment] 2018-02-28 17:20
@sylwiabr Since #149 is now closed, should I try again to install?

**Comment by sylwiabr** [comment] 2018-03-05 08:50
@BatmanAoD you should be able to install newest luna-studio with last manager/installer

**Comment by BatmanAoD** [comment] 2018-03-07 00:09
@sylwiabr I eventually did get 1.2 to install! Weirdly, I had to manually launch the installer in admin mode, even though I was given the "permit changes" prompt even when I launched it normally.

**Comment by sylwiabr** [comment] 2018-03-07 08:04
@BatmanAoD  Great! If the problems with installer will appear within next versions (it should appear soon) could you create a separate issue for this or write to us? Can we close this one?

**Closed** 2018-03-07 17:06 UTC

**Comment by ricardopieper** [comment] 2019-07-01 04:40
This just happened to me on Mac. It stopped downloading at 55%, then I closed the downloader, tried again, and it just shows:

You have this version already installed: 1.8
Manager version: 1.1.4
