### ISSUE TITLE
luna-manager develop crashes on python installation on MacOS High Sierra (10.13)

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-manager#52] opened 2017-10-24 10:59 UTC
There is an missing openssl error, even though it is installed using Homebrew. Seems connected to [this pyenv issue (#950)](https://github.com/pyenv/pyenv/issues/950).

This is the full output:
```
stack --resolver lts-8.2 --install-ghc runghc --package base --package exceptions --package shelly --package text --package directory --package system-filepath -- -hide-all-packages /Users/moczur/code/luna-studio/luna-develop/apps/luna-studio/bootstrap.hs
installing python locally
export PATH="/Users/moczur/code/luna-studio/../../tools/python/pyenv/shims:${PATH}"
export PYENV_SHELL=ghc
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")";;
  *)
    command pyenv "$command" "$@";;
  esac
}
Downloading Python-3.6.2.tar.xz...
-> https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz
Installing Python-3.6.2...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.13 using python-build 1.1.5-12-ga2d00cb)

Inspect or clean up the working tree at /var/folders/jd/md0fsfwn2yg_l14hb9zm3t140000gn/T/python-build.20171024125248.33357
Results logged to /var/folders/jd/md0fsfwn2yg_l14hb9zm3t140000gn/T/python-build.20171024125248.33357.log

Last 10 log lines:
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
bootstrap.hs:
Ran commands:
echo 'installing python locally'
mkdir -p /Users/moczur/code/luna-studio/../../tools/python
cd /Users/moczur/tools/python
prependToPath: /Users/moczur/code/luna-studio/../../tools/python/pyenv/bin
prependToPath: /Users/moczur/code/luna-studio/../../tools/python/pyenv/shims
pyenv init -
which pyenv
pyenv install 3.6.2
which pyenv
cd /Users/moczur/code/luna-studio

Exception: error running: pyenv install 3.6.2
exit status: 1
stderr: Downloading Python-3.6.2.tar.xz...
-> https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz
Installing Python-3.6.2...
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 10.13 using python-build 1.1.5-12-ga2d00cb)

Inspect or clean up the working tree at /var/folders/jd/md0fsfwn2yg_l14hb9zm3t140000gn/T/python-build.20171024125248.33357
Results logged to /var/folders/jd/md0fsfwn2yg_l14hb9zm3t140000gn/T/python-build.20171024125248.33357.log

Last 10 log lines:
			upgrade) ensurepip="--upgrade" ;; \
			install|*) ensurepip="" ;; \
		esac; \
		 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
```

**Comment by binary132** [comment] 2018-02-10 16:42
I too have this issue ☝️

**Comment by binary132** [comment] 2018-02-10 17:03
I believe this is the cause of the issue:

>https://github.com/luna/luna-studio/blob/230c136a9c52e39c3af64a92c64dce035c275516/bootstrap.hs#L91

```hs
 opensslPath <- Shelly.cmd "brew" "--prefix" "openssl"
```

As you can see by the following output, the newline in this command is included in the value of `opensslPath`.

I'm not familiar with Haskell, but I'll see if I can tweak this.  Ultimately, relying on the output format (or existence) of `brew` is a mistake that should be corrected.

---

> output

```
configure:3929: checking whether the C compiler works
configure:3951: clang -I/usr/local/opt/openssl
/include  -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/../../tools/python/pyenv/versions/3.6.2/include  -L/
/lib conftest.c  >&5
clang: error: no such file or directory: '/include'
clang: error: no such file or directory: '/lib'
configure:3955: $? = 1
configure:3993: result: no
configure: failed program was:
| /* confdefs.h */
| #define _GNU_SOURCE 1
| #define _NETBSD_SOURCE 1
| #define __BSD_VISIBLE 1
| #define _BSD_TYPES 1
| #define _DARWIN_C_SOURCE 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3998: error: in `/var/folders/ny/816mg0xs6z92jq9hl188bwz40000gn/T/python-build.20180210115727.1768/Python-3.6.2':
configure:4000: error: C compiler cannot create executables
See `config.log' for more details```

**Comment by binary132** [comment] 2018-02-10 17:15
This is actually a bug in the Luna Studio bootstrap.

**Comment by binary132** [comment] 2018-02-10 19:03
This is fixed in `luna-studio` as of https://github.com/luna/luna-studio/pull/810 .

**Comment by wdanilo** [comment] 2018-02-10 19:21
So can we close this one?

**Comment by binary132** [comment] 2018-02-11 00:21
Yes

**Closed** 2018-02-15 14:16 UTC
Labels: bug
